### ISSUE TITLE
Where are dynamic rules taken from?

### ISSUE THREAD

**Issue by PostScripton** [xagler/dynamic-rules#3]
Hi! I'm extremely interested in where you get theses dynamic rules from? Could you share this information please?

**Comment by xagler** [comment]
It's generated from OF source

**Comment by PostScripton** [comment]
Yeah, I mean how do you get this information from source? Reverse Engineering, deobfuscation and so on. Could you please share this knowledge?

**Comment by PostScripton** [comment]
Because I'm aiming to contribute to this project and keep those rules up to date

**Comment by PostScripton** [comment]
We could discuss it in more details further if you wish. I could give you my contacts

**Comment by xagler** [comment]
> We could discuss it in more details further if you wish. I could give you my contacts

contact me in tg: xagler
